#!/bin/sh
#
#   backup fsi install source
#
#   This program is free software; you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software Foundation;
#   either version 3 of the License, or (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#   without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#   See the GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License along with this program;
#   if not, see <http://www.gnu.org/licenses/>.
#
ver="1.0.8 - 8.8.2016"
retc=0
ls=""
progname=${0##*/}
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
SCRIPTSTART=$(date +%s.%N)
while [ -h "$SOURCE" ]; do
   SOURCE="$(readlink "$SOURCE")"
   [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
   DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done

export progdir="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

. $progdir/etc/func.sh
prgzip="/usr/bin/zip"

function help() {
   #clear
   echo
   tput setaf 2
   echo " Help for $progname - $ver"
   tput sgr0
   echo
   echo "  backup fsi install source"
   echo
   tput setaf 3
   echo "  Backup Dir Parameter:"
   tput sgr0
   echo "   -d <base dir>     base dir to create backup dir"
   echo "                     default $progdir/../../backup"
   echo
   tput setaf 3
   echo "  Job Parameter:"
   tput sgr0
   echo "   -e                backup all esxi source"
   echo "   -x                backup all xenserver source"
   echo "   -r                backup all linux redhat source"
   echo "   -c                backup all linux centos source"   
   echo "   -u                backup all esxi update source dirs"
   echo "   -p                backup all xenserver update source dirs"   
   echo "   -a                backup all"
   echo
   tput setaf 3
   echo "  Optional Parameter:"
   tput sgr0
   echo "   -q                quiet mode"
   echo "   -0/1/2            info/debug/trace mode"
   echo "   -l <logfile>      other logfile"
   echo
   tput setaf 3
   echo "  Return Code:"
   tput sgr0
   echo "    1 = help"
   echo "    2 = no job given "
   echo "    3 = no base backup dir exist - create"
   echo "    5 = no $prgzip found"
   echo "    > = different meaning"
   echo
   tput setaf 3
   echo "  Example:"
   tput sgr0
   echo "    $progname -e -d /opt/backup"
   echo "    $progname -a"
   echo
}


instesxi=0
instxen=0
instrh=0
instco=0
updxen=0
updesxi=0

basedir=""
backdir=""

if ! [ -f $prgzip ]; then
   echo "no $prgzip exist - abort"
   exit 5
fi

while getopts ":exrcaupd:l:hHq012" optname; do
   #tracemsg "Option $optname has value $OPTARG"
   case "$optname" in
      "H")
         printf '%20s - %s\n' "$progname" "backup fsi install sources"
         exit 1
      ;;
      "h")
         help
         exit 1
      ;;
      "q")
         export deb2scr="no"
         quietmode=" -q "
         #debmsg " quiet mode"
      ;;
      "0")
         export deb2scr="yes"
         export debug="info"
         quietmode=" -0 "
         debmsg " info mode"
      ;;
      "1")
         export deb2scr="yes"
         export debug="debug"
         quietmode=" -1 "
         debmsg " debug mode"
      ;;
      "2")
         export deb2scr="yes"
         export debug="trace"
         quietmode=" -2 "
         debmsg " trace mode"
      ;;
      "l")
         export logfile="$OPTARG"
         debmsg " log: $logfile"
      ;;
      "d")
         basedir="$OPTARG"
         debmsg " base dir: $basedir"
      ;;
      "e")
         instesxi=1
      ;;
      "x")
         instxen=1
      ;;
      "r")
         instrh=1
      ;;
      "p")
         updxen=1
      ;;
      "u")
         updesxi=1
      ;;
      "c")
         instco=1
      ;;
      "a")
         instesxi=1
         instxen=1
         instrh=1
         instco=1
         updxen=1
         updesxi=1
      ;;
      "?")
         errmsg "Unknown option $OPTARG"
      ;;
      ":")
         errmsg "No argument value for option $OPTARG"
      ;;
      *)
         # Should not occur
         errmsg "Unknown error while processing options"
      ;;
   esac
done


function create_backdir() {
   local retc=0
   tracemsg "$ls  Function [$FUNCNAME] startet"
   ls="$ls  "
   
   debmsg "$ls check if base dir exist"
   if [ -d $basedir ]; then
      debmsg "$ls basedir exist"
      
      local datetimestamp=$(date +%Y%m%d%H%M%S)
      backdir="$basedir/fib-$datetimestamp"
      
      infmsg "$ls backup dir $backdir"
      output=$(2>&1 mkdir -p $backdir)
      retc=$?
      if [ $retc -ne 0 ]; then
         errmsg "error creating backup dir $backdir"
         errmsg "output:$output"
      fi
   else
      errmsg "no base dir exist - create first"
      retc=3
   fi
   
   ls=${ls:0:${#ls}-2}
   tracemsg "$ls  Function [$FUNCNAME] ended - rc=$retc"
   return $retc
}


function backup_source() {
   local retc=0
   tracemsg "$ls  Function [$FUNCNAME] startet"
   ls="$ls  "

   local dir2bak=$1    # "$progdir/../../inst"
   tracemsg "$ls  dir2bak: $dir2bak"
   local what2bak=$2   # "rh"
   tracemsg "$ls  what2bak: $what2bak"
   local targetbak=$3  # "img"
   tracemsg "$ls  targetbak: $targetbak"
   
   
   pushd $dir2bak 2>&1  1>/dev/null
   tracemsg "$ls  dir: $(pwd)"
   
   for i in $(ls -d ${what2bak}*); do 
      dir_contains "$dir2bak/$i"
      contains=$?
      if [ $contains -eq 0 ]; then
         infmsg "$ls backup $dir2bak/$i"
         local tempi=${i//\//_}
         cmd="/usr/bin/zip -y -r $backdir/fsi${targetbak}_$tempi $i"
         tracemsg "$ls  cmd: $cmd"
         output=$(2>&1 $cmd)
         retc=$?
         if [ $retc -ne 0 ]; then
            errmsg "cannot backup $i - abort"
            break
         fi
      elif [ $contains -eq 1 ]; then
         warnmsg "$ls $dir2bak/$i dir is empty"
      elif [ $contains -eq 2 ]; then
         warnmsg "$ls $dir2bak/$i dir does not exist $dir2bak"
      else
         errmsg "error detecting $dir2bak"
      fi
   done
   popd 2>&1 1>/dev/null
   
   ls=${ls:0:${#ls}-2}
   tracemsg "$ls  Function [$FUNCNAME] ended - rc=$retc"
   return $retc
}




if [ $instesxi -eq 0 ] && [ $instxen -eq 0 ] && [ $instrh -eq 0 ] && [ $instco -eq 0 ] && [ $updxen -eq 0 ] && [ $updesxi -eq 0 ]; then
   help
   exit 2
fi


debmsg "Start $progname - $ver"

if [ -z $basedir ]; then
   basedir="$progdir/../../backup"
   infmsg "$ls take default backup dir $basedir"
else
   infmsg "$ls backup dir $basedir"
fi

tracemsg "$ls  create backup dir in base dir"
create_backdir
retc=$?

if [ $retc -eq 0 ]; then
   if [ $instesxi -eq 1 ]; then
      infmsg "$ls backup esxi source"
      backup_source "$progdir/../../pxe/img" "esxi" "img"
      retc=$?
      if [ $retc -eq 0 ]; then
         backup_source "$progdir/../../inst" "esxi" "inst"
         retc=$?
      fi
   fi
fi
if [ $retc -eq 0 ]; then
   if [ $instxen -eq 1 ]; then
      infmsg "$ls backup xenserver source"
      backup_source "$progdir/../../pxe/img" "xen" "img"
      retc=$?
      if [ $retc -eq 0 ]; then
         backup_source "$progdir/../../inst" "xen" "inst"
         retc=$?
      fi
   fi
fi
if [ $retc -eq 0 ]; then
   if [ $instrh -eq 1 ]; then
      infmsg "$ls backup redhat source"
      backup_source "$progdir/../../pxe/img" "rh" "img"
      retc=$?
      if [ $retc -eq 0 ]; then
         backup_source "$progdir/../../inst" "rh" "inst"
         retc=$?
      fi
   fi
fi
if [ $retc -eq 0 ]; then
   if [ $instco -eq 1 ]; then
      infmsg "$ls backup centos source"
      backup_source "$progdir/../../pxe/img" "co" "img"
      retc=$?
      if [ $retc -eq 0 ]; then
         backup_source "$progdir/../../inst" "co" "inst"
         retc=$?
      fi
   fi
fi

if [ $retc -eq 0 ]; then
   if [ $updxen -eq 1 ]; then
      infmsg "$ls backup xenserver update source dir"
      backup_source "$progdir/../../inst" "xen*/ks/upd" "updxen"
      retc=$?
   fi
fi

if [ $retc -eq 0 ]; then
   if [ $updesxi -eq 1 ]; then
      infmsg "$ls backup esxi update source dir"
      backup_source "$progdir/../../inst" "esxi*/ks/upd" "updesxi"
      retc=$?
   fi
fi


SCRIPTEND=$(date +%s.%N)
runningtime=$(echo "$SCRIPTEND - $SCRIPTSTART" | bc)
debmsg "End $progname rc=$retc run=$runningtime"
exit $retc



